#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
# autospec version: v2
# autospec commit: f032afc
#
Name     : pypi-nh3
Version  : 0.2.14
Release  : 2
URL      : https://files.pythonhosted.org/packages/b0/bb/e967b7bc659cd1fd87f845d02194a08ea8da88d7d9dcc28164ee513f76f3/nh3-0.2.14.tar.gz
Source0  : https://files.pythonhosted.org/packages/b0/bb/e967b7bc659cd1fd87f845d02194a08ea8da88d7d9dcc28164ee513f76f3/nh3-0.2.14.tar.gz
Source1  : http://localhost/cgit/vendor/pypi-nh3/snapshot/pypi-nh3-2023-10-17-01-57-42.tar.xz
Summary  : Ammonia HTML sanitizer Python binding
Group    : Development/Tools
License  : Apache-2.0 MIT Unicode-DFS-2016 Zlib
Requires: pypi-nh3-license = %{version}-%{release}
Requires: pypi-nh3-python = %{version}-%{release}
Requires: pypi-nh3-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(maturin)
BuildRequires : pypi-maturin
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# nh3
![CI](https://github.com/messense/nh3/workflows/CI/badge.svg)
[![PyPI](https://img.shields.io/pypi/v/nh3.svg)](https://pypi.org/project/nh3)
[![Documentation Status](https://readthedocs.org/projects/nh3/badge/?version=latest)](https://nh3.readthedocs.io/en/latest/?badge=latest)

%package license
Summary: license components for the pypi-nh3 package.
Group: Default

%description license
license components for the pypi-nh3 package.


%package python
Summary: python components for the pypi-nh3 package.
Group: Default
Requires: pypi-nh3-python3 = %{version}-%{release}

%description python
python components for the pypi-nh3 package.


%package python3
Summary: python3 components for the pypi-nh3 package.
Group: Default
Requires: python3-core
Provides: pypi(nh3)

%description python3
python3 components for the pypi-nh3 package.


%prep
%setup -q -n nh3-0.2.14
cd %{_builddir}
tar xf %{_sourcedir}/pypi-nh3-2023-10-17-01-57-42.tar.xz
cd %{_builddir}/nh3-0.2.14
mkdir -p ./vendor
cp -r %{_builddir}/pypi-nh3-2023-10-17-01-57-42/* %{_builddir}/nh3-0.2.14/./vendor
mkdir -p .cargo
echo '[source.crates-io]' >> .cargo/config.toml
echo 'replace-with = "vendored-sources"' >> .cargo/config.toml
echo '[source.vendored-sources]' >> .cargo/config.toml
echo 'directory = "vendor"' >> .cargo/config.toml
pushd ..
cp -a nh3-0.2.14 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1697513635
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -m64 -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-nh3
cp %{_builddir}/nh3-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-nh3/8c2d955bc44f49a3d3e24b6ada2a427746858218 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/ammonia/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-nh3/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/ammonia/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-nh3/e6c3cd8165498c27af60e5237edfb87eebeff337 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/autocfg/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-nh3/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/autocfg/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-nh3/e6d32072ef5f584a805b429ecbd4eec428316dde || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/bitflags/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-nh3/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/bitflags/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-nh3/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/cfg-if/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-nh3/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/cfg-if/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-nh3/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/form_urlencoded/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-nh3/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/form_urlencoded/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-nh3/738188f5fed28a950b0fede659706238ec35f8bb || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/futf/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-nh3/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/futf/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-nh3/6fc7897021205e271da51720736b06f9b5df3538 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/getrandom/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-nh3/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/getrandom/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-nh3/d74ad13f1402c35008f22bc588a6b8199ed164d3 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/html5ever/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-nh3/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/html5ever/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-nh3/7f358d75b6f5bd544ce84621510900e11b27d3ba || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/idna/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-nh3/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/idna/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-nh3/a81399b7c3ec2d4619848fd59c11d21211fc3b86 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/indoc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-nh3/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/indoc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-nh3/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/libc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-nh3/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/libc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-nh3/36d69bcb88153a640740000efe933b009420ce7e || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/lock_api/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-nh3/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/lock_api/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-nh3/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/log/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-nh3/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/log/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-nh3/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/maplit/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-nh3/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/maplit/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-nh3/3a86cfdfa553511b381388859c9e94ce9e1f916b || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/markup5ever/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-nh3/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/markup5ever/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-nh3/7f358d75b6f5bd544ce84621510900e11b27d3ba || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/memoffset/LICENSE %{buildroot}/usr/share/package-licenses/pypi-nh3/02bf11a87b9bbacedf2fcf4856af3b933faef82e || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/new_debug_unreachable/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-nh3/108bb98fdf8f27765ea240d80481be8362175ca7 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/once_cell/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-nh3/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/once_cell/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-nh3/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/parking_lot/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-nh3/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/parking_lot/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-nh3/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/parking_lot_core/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-nh3/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/parking_lot_core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-nh3/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/percent-encoding/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-nh3/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/percent-encoding/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-nh3/a81399b7c3ec2d4619848fd59c11d21211fc3b86 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/ppv-lite86/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-nh3/088830dcb78eba1a2052df69bd5cba5445e8f2d7 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/ppv-lite86/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-nh3/e1c86f32641f01a5b85d6e9b20138e8470b883fc || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/precomputed-hash/LICENSE %{buildroot}/usr/share/package-licenses/pypi-nh3/afcd08e00b65f2380ab5b0aa0217e8d62aa3cb2a || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/proc-macro2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-nh3/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/proc-macro2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-nh3/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/pyo3-build-config/LICENSE %{buildroot}/usr/share/package-licenses/pypi-nh3/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/pyo3-macros-backend/LICENSE %{buildroot}/usr/share/package-licenses/pypi-nh3/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/pyo3-macros/LICENSE %{buildroot}/usr/share/package-licenses/pypi-nh3/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/pyo3/LICENSE %{buildroot}/usr/share/package-licenses/pypi-nh3/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/quote/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-nh3/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/quote/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-nh3/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/rand/COPYRIGHT %{buildroot}/usr/share/package-licenses/pypi-nh3/f14afa20edce530124d39cd56312c7781c19b267 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/rand/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-nh3/4632a631b427f005d97734ea8c6a44090fec5cd9 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/rand/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-nh3/d74ad13f1402c35008f22bc588a6b8199ed164d3 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/rand_chacha/COPYRIGHT %{buildroot}/usr/share/package-licenses/pypi-nh3/f14afa20edce530124d39cd56312c7781c19b267 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/rand_chacha/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-nh3/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/rand_chacha/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-nh3/d74ad13f1402c35008f22bc588a6b8199ed164d3 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/rand_core/COPYRIGHT %{buildroot}/usr/share/package-licenses/pypi-nh3/f14afa20edce530124d39cd56312c7781c19b267 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/rand_core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-nh3/d74ad13f1402c35008f22bc588a6b8199ed164d3 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/redox_syscall/LICENSE %{buildroot}/usr/share/package-licenses/pypi-nh3/a00165152c82ea55b9fc254890dc8860c25e3bb6 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/scopeguard/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-nh3/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/scopeguard/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-nh3/f498d95a48889a0b1432e420e6754881eff1d593 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/serde/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-nh3/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/serde/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-nh3/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/siphasher/COPYING %{buildroot}/usr/share/package-licenses/pypi-nh3/89dd598543231b6010a8d57e5cd4f31331fe5364 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/smallvec/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-nh3/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/smallvec/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-nh3/c61640f6c218caf86d1b8072e09668a8362dba04 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/string_cache/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-nh3/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/string_cache/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-nh3/6c2945f449081ab19640fb7c70a081a1a4559399 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/string_cache_codegen/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-nh3/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/string_cache_codegen/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-nh3/6c2945f449081ab19640fb7c70a081a1a4559399 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/syn/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-nh3/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/syn/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-nh3/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/target-lexicon/LICENSE %{buildroot}/usr/share/package-licenses/pypi-nh3/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/tendril/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-nh3/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/tendril/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-nh3/6fc7897021205e271da51720736b06f9b5df3538 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/tinyvec/LICENSE-APACHE.md %{buildroot}/usr/share/package-licenses/pypi-nh3/47b573e3824cd5e02a1a3ae99e2735b49e0256e4 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/tinyvec/LICENSE-MIT.md %{buildroot}/usr/share/package-licenses/pypi-nh3/ee70bf5efb387a6c52c0f5cbea4122c6a74a57bb || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/tinyvec/LICENSE-ZLIB.md %{buildroot}/usr/share/package-licenses/pypi-nh3/59b5efd50c4508e7fa74828e7469187bbe5bd864 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/tinyvec_macros/LICENSE-APACHE.md %{buildroot}/usr/share/package-licenses/pypi-nh3/8cc042e8e4b82c5532c72172a1988a74a599d4b5 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/tinyvec_macros/LICENSE-MIT.md %{buildroot}/usr/share/package-licenses/pypi-nh3/86d193cb6b24df990cbbaf67c6a24fddbcb574c1 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/unicode-bidi/COPYRIGHT %{buildroot}/usr/share/package-licenses/pypi-nh3/871b9912ab96cf7d79cb8ae83ca0b08cd5d0cbfd || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/unicode-bidi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-nh3/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/unicode-bidi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-nh3/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/unicode-ident/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-nh3/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/unicode-ident/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-nh3/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/unicode-ident/LICENSE-UNICODE %{buildroot}/usr/share/package-licenses/pypi-nh3/583a5eebcf6119730bd96922e8a0faecf7faf720 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/unicode-normalization/COPYRIGHT %{buildroot}/usr/share/package-licenses/pypi-nh3/5ed53061419caf64f84d064f3641392a2a10fa7f || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/unicode-normalization/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-nh3/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/unicode-normalization/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-nh3/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/unindent/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-nh3/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/unindent/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-nh3/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/url/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-nh3/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/url/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-nh3/a81399b7c3ec2d4619848fd59c11d21211fc3b86 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/utf-8/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-nh3/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/utf-8/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-nh3/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/wasi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-nh3/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/wasi/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/pypi-nh3/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/wasi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-nh3/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/windows-targets/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-nh3/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/windows-targets/license-mit %{buildroot}/usr/share/package-licenses/pypi-nh3/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/windows_aarch64_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-nh3/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/windows_aarch64_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/pypi-nh3/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/windows_aarch64_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-nh3/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/windows_aarch64_msvc/license-mit %{buildroot}/usr/share/package-licenses/pypi-nh3/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/windows_i686_gnu/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-nh3/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/windows_i686_gnu/license-mit %{buildroot}/usr/share/package-licenses/pypi-nh3/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/windows_i686_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-nh3/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/windows_i686_msvc/license-mit %{buildroot}/usr/share/package-licenses/pypi-nh3/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/windows_x86_64_gnu/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-nh3/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/windows_x86_64_gnu/license-mit %{buildroot}/usr/share/package-licenses/pypi-nh3/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/windows_x86_64_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-nh3/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/windows_x86_64_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/pypi-nh3/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/windows_x86_64_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-nh3/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-nh3-2023-10-17-01-57-42/windows_x86_64_msvc/license-mit %{buildroot}/usr/share/package-licenses/pypi-nh3/689ec0681815ecc32bee639c68e7740add7bd301 || :
python3 -m installer --destdir=%{buildroot} dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -m64 -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -m64 -march=x86-64-v3 "
python3 -m installer --destdir=%{buildroot}-v3 dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-nh3/02bf11a87b9bbacedf2fcf4856af3b933faef82e
/usr/share/package-licenses/pypi-nh3/088830dcb78eba1a2052df69bd5cba5445e8f2d7
/usr/share/package-licenses/pypi-nh3/108bb98fdf8f27765ea240d80481be8362175ca7
/usr/share/package-licenses/pypi-nh3/36d69bcb88153a640740000efe933b009420ce7e
/usr/share/package-licenses/pypi-nh3/3a86cfdfa553511b381388859c9e94ce9e1f916b
/usr/share/package-licenses/pypi-nh3/3b042d3d971924ec0296687efd50dbe08b734976
/usr/share/package-licenses/pypi-nh3/4632a631b427f005d97734ea8c6a44090fec5cd9
/usr/share/package-licenses/pypi-nh3/47b573e3824cd5e02a1a3ae99e2735b49e0256e4
/usr/share/package-licenses/pypi-nh3/5798832c31663cedc1618d18544d445da0295229
/usr/share/package-licenses/pypi-nh3/583a5eebcf6119730bd96922e8a0faecf7faf720
/usr/share/package-licenses/pypi-nh3/59b5efd50c4508e7fa74828e7469187bbe5bd864
/usr/share/package-licenses/pypi-nh3/5bb5828e544f63bd76c1b7112981a1ad86ae77f9
/usr/share/package-licenses/pypi-nh3/5ed53061419caf64f84d064f3641392a2a10fa7f
/usr/share/package-licenses/pypi-nh3/60c3522081bf15d7ac1d4c5a63de425ef253e87a
/usr/share/package-licenses/pypi-nh3/669a1e53b9dd9df3474300d3d959bb85bad75945
/usr/share/package-licenses/pypi-nh3/689ec0681815ecc32bee639c68e7740add7bd301
/usr/share/package-licenses/pypi-nh3/6c2945f449081ab19640fb7c70a081a1a4559399
/usr/share/package-licenses/pypi-nh3/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a
/usr/share/package-licenses/pypi-nh3/6fc7897021205e271da51720736b06f9b5df3538
/usr/share/package-licenses/pypi-nh3/738188f5fed28a950b0fede659706238ec35f8bb
/usr/share/package-licenses/pypi-nh3/7f358d75b6f5bd544ce84621510900e11b27d3ba
/usr/share/package-licenses/pypi-nh3/86d193cb6b24df990cbbaf67c6a24fddbcb574c1
/usr/share/package-licenses/pypi-nh3/871b9912ab96cf7d79cb8ae83ca0b08cd5d0cbfd
/usr/share/package-licenses/pypi-nh3/89dd598543231b6010a8d57e5cd4f31331fe5364
/usr/share/package-licenses/pypi-nh3/8c2d955bc44f49a3d3e24b6ada2a427746858218
/usr/share/package-licenses/pypi-nh3/8cc042e8e4b82c5532c72172a1988a74a599d4b5
/usr/share/package-licenses/pypi-nh3/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7
/usr/share/package-licenses/pypi-nh3/9f3c36d2b7d381d9cf382a00166f3fbd06783636
/usr/share/package-licenses/pypi-nh3/a00165152c82ea55b9fc254890dc8860c25e3bb6
/usr/share/package-licenses/pypi-nh3/a3b3a65335e78bde163f84d599fa899776552994
/usr/share/package-licenses/pypi-nh3/a81399b7c3ec2d4619848fd59c11d21211fc3b86
/usr/share/package-licenses/pypi-nh3/afcd08e00b65f2380ab5b0aa0217e8d62aa3cb2a
/usr/share/package-licenses/pypi-nh3/c61640f6c218caf86d1b8072e09668a8362dba04
/usr/share/package-licenses/pypi-nh3/ce3a2603094e799f42ce99c40941544dfcc5c4a5
/usr/share/package-licenses/pypi-nh3/d74ad13f1402c35008f22bc588a6b8199ed164d3
/usr/share/package-licenses/pypi-nh3/e1c86f32641f01a5b85d6e9b20138e8470b883fc
/usr/share/package-licenses/pypi-nh3/e6c3cd8165498c27af60e5237edfb87eebeff337
/usr/share/package-licenses/pypi-nh3/e6d32072ef5f584a805b429ecbd4eec428316dde
/usr/share/package-licenses/pypi-nh3/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e
/usr/share/package-licenses/pypi-nh3/ee70bf5efb387a6c52c0f5cbea4122c6a74a57bb
/usr/share/package-licenses/pypi-nh3/f137043e018f2024e0414a9153ea728c203ae8e5
/usr/share/package-licenses/pypi-nh3/f14afa20edce530124d39cd56312c7781c19b267
/usr/share/package-licenses/pypi-nh3/f498d95a48889a0b1432e420e6754881eff1d593

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/V3/usr/lib/python3*/*
/usr/lib/python3*/*
